services:
  - type: web
    name: auditarest
    env: php
    region: oregon
    buildCommand: |
      # Instalar dependencias de PHP
      composer install --no-dev --optimize-autoloader --no-interaction
      
      # Instalar dependencias de Node.js
      npm install
      npm run build
      
      # Configuración de caché
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
    startCommand: "php artisan serve --host=0.0.0.0 --port=${PORT}"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        fromHost: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: auditarest-db
          property: hostname
      - key: DB_PORT
        value: '5432'
      - key: DB_DATABASE
        fromDatabase:
          name: auditarest-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: auditarest-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: auditarest-db
          property: password
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: debug

databases:
  - name: auditarest-db
    databaseName: auditarest
    user: auditarest_user
    plan: free
    engine: postgres
    version: "14"