services:
  - type: web
    name: auditarest
    env: docker
    region: oregon
    dockerContext: .
    dockerfile: Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        fromHost: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: auditarest-db
          property: hostname
      - key: DB_PORT
        value: '5432'
      - key: DB_DATABASE
        fromDatabase:
          name: auditarest-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: auditarest-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: auditarest-db
          property: password

databases:
  - name: auditarest-db
    databaseName: auditarest
    user: auditarest_user
    plan: free